name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install packages
      run: sudo apt -qq update && sudo apt -y -qq install libusb-1.0-0-dev dh-autoreconf --no-install-recommends
    - name: get sources
      run: git clone https://github.com/rockchip-linux/rkdeveloptool.git
    - name: configure
      run: cd rkdeveloptool && autoreconf -i && ./configure
    - name: make
      run: cd rkdeveloptool && make
    - name: Cache
      uses: actions/cache@v1.2.0
      with:
      # A directory to store and save the cache
        path: ~/rkdeveloptool 
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-rkdevelop-bin
