name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get sources
      run: git clone https://github.com/rockchip-linux/rkdeveloptool.git && 
    - name: configure
      run: cd rkdeveloptool && autoreconf -i && ./confgire
    - name: make
      run: make
    - name: Create a Release
      uses: actions/create-release@v1
