# This is a basic workflow to help you get started with Actions

name: Create release

on:
  create:
    branches: [ master ]

jobs:
  manage-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.html_url }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create a Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
          tag_name: github.ref
        # The name of the release. For example, `Release v1.0.1`
          release_name: github.ref
      - name: Cache refresh
        uses: actions/cache@v1.2.0
        with:
        # A directory to store and save the cache
          path: ~/rkdeveloptool 
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-rkdevelop-bin 
      - name: Upload a Release Asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          # The URL for uploading assets to the release
          upload_url: 
          # The path to the asset you want to upload
          asset_path: 
          # The name of the asset you want to upload
          asset_name: 
          # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
          asset_content_type: 
