# This is a basic workflow to help you get started with Actions

name: Create release

on:
  create:
    branches: [ master ]

jobs:
  manage-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create a Release
        uses: actions/create-release@v1
        with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
          tag_name: github.ref
        # The name of the release. For example, `Release v1.0.1`
          release_name: github.ref
